var bands=document.getElementsByClassName("header-title");
var band=bands[0];
var a=document.createElement('a');
a.innerHTML="Search "+band.innerText+" on Yandex Music";
a.href="https://music.yandex.by/search?text="+band.innerText+"&type=artists";
var newDiv=document.createElement('div');
newDiv.style.width='200px';
newDiv.style.height='100px';
newDiv.appendChild(a);
var afterDivs=document.getElementsByClassName("featured-items-row");
var afterDiv=afterDivs[0];
var targets=document.getElementsByClassName("col-main");
var target=targets[0];
target.insertBefore(newDiv,afterDiv);
