var band=document.getElementsByClassName("header-title")[0];
var a=document.createElement('a');
a.innerHTML="Search "+band.innerText+" on Yandex Music";
a.href="https://music.yandex.by/search?text="+band.innerText+"&type=artists";
var newDiv=document.createElement('div');
newDiv.style.width='600px';
newDiv.style.height='40px';
newDiv.appendChild(a);
var afterDiv=document.getElementsByClassName("featured-items-row")[0];
var target=document.getElementsByClassName("col-main")[0];
target.insertBefore(newDiv,afterDiv);
